server {
    listen 80;
    server_name comfyui.com www.comfyui.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name comfyui.com www.comfyui.com;

    ssl_certificate /etc/nginx/ssl/comfyui.com.crt;
    ssl_certificate_key /etc/nginx/ssl/comfyui.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    root /var/www/comfyui;
    index index.html;

    location = /ads.txt {
        return 301 https://srv.adstxtmanager.com/19390/comfyui.com;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name 120.48.169.183;
    root /var/www/comfyui;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl http2;
    server_name 120.48.169.183;

    ssl_certificate /etc/nginx/ssl/comfyui.com.crt;
    ssl_certificate_key /etc/nginx/ssl/comfyui.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    root /var/www/comfyui;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
